export const ALL_QUESTIONS_REQUEST = "ALL_QUESTIONS_REQUEST";
export const ALL_QUESTIONS_SUCCESS = "ALL_QUESTIONS_SUCCESS";
export const ALL_QUESTIONS_FAIL = "ALL_QUESTIONS_FAIL";

export const QUESTION_DETAILS_REQUEST = "QUESTION_DETAILS_REQUEST";
export const QUESTION_DETAILS_SUCCESS = "QUESTION_DETAILS_SUCCESS";
export const QUESTION_DETAILS_FAIL = "QUESTION_DETAILS_FAIL";

export const ADMIN_QUESTIONS_REQUEST = "ADMIN_QUESTIONS_REQUEST";
export const ADMIN_QUESTIONS_SUCCESS = "ADMIN_QUESTIONS_SUCCESS";
export const ADMIN_QUESTIONS_FAIL = "ADMIN_QUESTIONS_FAIL";

export const NEW_QUESTION_REQUEST = "NEW_QUESTION_REQUEST";
export const NEW_QUESTION_SUCCESS = "NEW_QUESTION_SUCCESS";
export const NEW_QUESTION_RESET = "NEW_QUESTION_RESET";
export const NEW_QUESTION_FAIL = "NEW_QUESTION_FAIL";

export const DELETE_QUESTION_REQUEST = "DELETE_QUESTION_REQUEST";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const DELETE_QUESTION_RESET = "DELETE_QUESTION_RESET";
export const DELETE_QUESTION_FAIL = "DELETE_QUESTION_FAIL";

export const UPDATE_QUESTION_REQUEST = "UPDATE_QUESTION_REQUEST";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_RESET = "UPDATE_QUESTION_RESET";
export const UPDATE_QUESTION_FAIL = "UPDATE_QUESTION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
