export const ALL_STORES_REQUEST = "ALL_STORES_REQUEST";
export const ALL_STORES_SUCCESS = "ALL_STORES_SUCCESS";
export const ALL_STORES_FAIL = "ALL_STORES_FAIL";

export const STORE_DETAILS_REQUEST = "STORE_DETAILS_REQUEST";
export const STORE_DETAILS_SUCCESS = "STORE_DETAILS_SUCCESS";
export const STORE_DETAILS_FAIL = "STORE_DETAILS_FAIL";

export const ADMIN_STORES_REQUEST = "ADMIN_STORES_REQUEST";
export const ADMIN_STORES_SUCCESS = "ADMIN_STORES_SUCCESS";
export const ADMIN_STORES_FAIL = "ADMIN_STORES_FAIL";

export const NEW_STORE_REQUEST = "NEW_STORE_REQUEST";
export const NEW_STORE_SUCCESS = "NEW_STORE_SUCCESS";
export const NEW_STORE_RESET = "NEW_STORE_RESET";
export const NEW_STORE_FAIL = "NEW_STORE_FAIL";

export const DELETE_STORE_REQUEST = "DELETE_STORE_REQUEST";
export const DELETE_STORE_SUCCESS = "DELETE_STORE_SUCCESS";
export const DELETE_STORE_RESET = "DELETE_STORE_RESET";
export const DELETE_STORE_FAIL = "DELETE_STORE_FAIL";

export const UPDATE_STORE_REQUEST = "UPDATE_STORE_REQUEST";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const UPDATE_STORE_RESET = "UPDATE_STORE_RESET";
export const UPDATE_STORE_FAIL = "UPDATE_STORE_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
